quarkus.http.port=8181

kafka.bootstrap.servers=${KAFKA_BROKER:localhost:19092}
kafka.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:18081}
kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:prueba-new}
kafka.partition.default=${KAFKA_DEFAULT_PARTITION:1}
topic.name=${KAFKA_TOPIC:order-topic}

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n
